baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "A Hugo website"
theme = "hugo-sustain"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/blog/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Blog"
    url = "/blog/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/rstudio/blogdown"

[params]
    description = "My personal webpage built through Hugo and blogdown."
    avatar = "images/profile_small.jpg"
    author = "Andrew Duncan"
    
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.9.0"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

[params.social]
  Github        = "aj2duncan"
